spring.application.name=fileupload

spring.cloud.gcp.credentials.location=${GCP_CREDENTIALS_LOCATION:file:/home/admini/.config/gcloud/gcs-signer.json}

# GCP properties
gcp.bucket.name=example-upload-file
